/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripTripIdRouteImport } from './routes/trip.$tripId'
import { Route as ApiSessionRouteImport } from './routes/api.session'
import { Route as ApiSearchRouteImport } from './routes/api.search'
import { Route as ApiPlacesRouteImport } from './routes/api.places'
import { Route as ApiPlaceDetailsRouteImport } from './routes/api.place-details'
import { Route as ApiCurateRouteImport } from './routes/api.curate'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTripIdRoute = TripTripIdRouteImport.update({
  id: '/trip/$tripId',
  path: '/trip/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacesRoute = ApiPlacesRouteImport.update({
  id: '/api/places',
  path: '/api/places',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlaceDetailsRoute = ApiPlaceDetailsRouteImport.update({
  id: '/api/place-details',
  path: '/api/place-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCurateRoute = ApiCurateRouteImport.update({
  id: '/api/curate',
  path: '/api/curate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/curate': typeof ApiCurateRoute
  '/api/place-details': typeof ApiPlaceDetailsRoute
  '/api/places': typeof ApiPlacesRoute
  '/api/search': typeof ApiSearchRoute
  '/api/session': typeof ApiSessionRoute
  '/trip/$tripId': typeof TripTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/curate': typeof ApiCurateRoute
  '/api/place-details': typeof ApiPlaceDetailsRoute
  '/api/places': typeof ApiPlacesRoute
  '/api/search': typeof ApiSearchRoute
  '/api/session': typeof ApiSessionRoute
  '/trip/$tripId': typeof TripTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/curate': typeof ApiCurateRoute
  '/api/place-details': typeof ApiPlaceDetailsRoute
  '/api/places': typeof ApiPlacesRoute
  '/api/search': typeof ApiSearchRoute
  '/api/session': typeof ApiSessionRoute
  '/trip/$tripId': typeof TripTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/curate'
    | '/api/place-details'
    | '/api/places'
    | '/api/search'
    | '/api/session'
    | '/trip/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/curate'
    | '/api/place-details'
    | '/api/places'
    | '/api/search'
    | '/api/session'
    | '/trip/$tripId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/curate'
    | '/api/place-details'
    | '/api/places'
    | '/api/search'
    | '/api/session'
    | '/trip/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiCurateRoute: typeof ApiCurateRoute
  ApiPlaceDetailsRoute: typeof ApiPlaceDetailsRoute
  ApiPlacesRoute: typeof ApiPlacesRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSessionRoute: typeof ApiSessionRoute
  TripTripIdRoute: typeof TripTripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$tripId': {
      id: '/trip/$tripId'
      path: '/trip/$tripId'
      fullPath: '/trip/$tripId'
      preLoaderRoute: typeof TripTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/places': {
      id: '/api/places'
      path: '/api/places'
      fullPath: '/api/places'
      preLoaderRoute: typeof ApiPlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/place-details': {
      id: '/api/place-details'
      path: '/api/place-details'
      fullPath: '/api/place-details'
      preLoaderRoute: typeof ApiPlaceDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/curate': {
      id: '/api/curate'
      path: '/api/curate'
      fullPath: '/api/curate'
      preLoaderRoute: typeof ApiCurateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiCurateRoute: ApiCurateRoute,
  ApiPlaceDetailsRoute: ApiPlaceDetailsRoute,
  ApiPlacesRoute: ApiPlacesRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiSessionRoute: ApiSessionRoute,
  TripTripIdRoute: TripTripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
