/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripTripIdRouteImport } from './routes/trip.$tripId'
import { Route as ApiPlacesRouteImport } from './routes/api.places'
import { Route as ApiCurateRouteImport } from './routes/api.curate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTripIdRoute = TripTripIdRouteImport.update({
  id: '/trip/$tripId',
  path: '/trip/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacesRoute = ApiPlacesRouteImport.update({
  id: '/api/places',
  path: '/api/places',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCurateRoute = ApiCurateRouteImport.update({
  id: '/api/curate',
  path: '/api/curate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/curate': typeof ApiCurateRoute
  '/api/places': typeof ApiPlacesRoute
  '/trip/$tripId': typeof TripTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/curate': typeof ApiCurateRoute
  '/api/places': typeof ApiPlacesRoute
  '/trip/$tripId': typeof TripTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/curate': typeof ApiCurateRoute
  '/api/places': typeof ApiPlacesRoute
  '/trip/$tripId': typeof TripTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/curate' | '/api/places' | '/trip/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/curate' | '/api/places' | '/trip/$tripId'
  id: '__root__' | '/' | '/api/curate' | '/api/places' | '/trip/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCurateRoute: typeof ApiCurateRoute
  ApiPlacesRoute: typeof ApiPlacesRoute
  TripTripIdRoute: typeof TripTripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$tripId': {
      id: '/trip/$tripId'
      path: '/trip/$tripId'
      fullPath: '/trip/$tripId'
      preLoaderRoute: typeof TripTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/places': {
      id: '/api/places'
      path: '/api/places'
      fullPath: '/api/places'
      preLoaderRoute: typeof ApiPlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/curate': {
      id: '/api/curate'
      path: '/api/curate'
      fullPath: '/api/curate'
      preLoaderRoute: typeof ApiCurateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCurateRoute: ApiCurateRoute,
  ApiPlacesRoute: ApiPlacesRoute,
  TripTripIdRoute: TripTripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
